name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
    - main 

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v2.0.0
        with:
          dotnet-version: 5.0.x
      - name: Restore dependiences
        run: dotnet restore ./RestaurantAPI.sln
      - name: Bulid
        run: dotnet build ./RestaurantAPI/RestaurantAPI.csproj--no-restore
      - name: Test
        run: dotnet test
